version: "3.7"

services:
  ams-backend-service:
    container_name: ams-backend_container
    image: ams-backend-img
    build:
      context: ams-backend
    ports:
      - "8080:8080"
    volumes:
      - "./ams-backend/target/:/home/ams_user"
    networks:
      - ams-network
    command: java -jar /home/ams_user/ams-backend-0.0.1-SNAPSHOT.jar com.onur.akan.ams.AmsApplication 
networks:
  ams-network:
